[package]
name = "lambda_sqs"
version = "0.2.3"
description = """
Handles an SQS event and provides a vec of your type for processing. 
"""
edition = "2018"
authors = ["Jeremiah Russell <jrussell@jerus.ie>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jerusdp/lambda_sqs"
readme = "README.md"
documentation = "https://docs.rs/lambda-sqs"
categories = ["web-programming"]
keywords = ["aws", "sqs", "lambda"]
exclude = [
    ".fossa.yml",
    ".github/workflows/fossa.yml",
    ".github/workflows/general.yml",
    ".github/workflows/rust_security_audit.yml",
    ".gitignore",
    ".vscode/settings.json",
    ".whitesource",
    "markdownlint.jsonc",
    "renovate.json"
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lambda_runtime = "0.7.0"

[dev-dependencies]
tokio = "1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

