[package]
name = "lambda_sqs"
version = "0.1.0"
edition = "2018"
authors = ["Jeremiah Russell <jrussell@jerus.ie>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/jerusdp/lambda-sqs"
readme = "README.md"
documentation = "https://docs.rs/lambda-sqs"
categories = ["web-programming"]
keywords = ["aws", "sqs", "lambda"]

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
lambda_runtime = "0.4.1"