
pre-release-replacements = [
    { file = "README.md", search = "lambda_sqs = .*", replace = "{{crate_name}} = \" {{version}}\"" },
    { file = "src/lib.rs", search = "lambda_sqs = .*", replace = "{{crate_name}} = \" {{{version}}\"" },
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]:", replace = "[{{version}}]:", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
]
